# Generated by Django 2.0.2 on 2018-02-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_test', '0002_auto_20180214_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawling',
            old_name='daum_result',
            new_name='daum_blog',
        ),
        migrations.RenameField(
            model_name='crawling',
            old_name='naver_result',
            new_name='daum_cafe',
        ),
        migrations.AddField(
            model_name='crawling',
            name='daum_web',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='crawling',
            name='naver_blog',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='crawling',
            name='naver_cafe',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='crawling',
            name='naver_news',
            field=models.TextField(null=True),
        ),
    ]
